In [1]:
import numpy as np

## Generating randoms

In [2]:
np.random.rand(3, 3)

array([[0.91258363, 0.36210106, 0.75171521],
       [0.2295632 , 0.81385726, 0.73229797],
       [0.24809842, 0.75707077, 0.29193488]])

In [3]:
np.random.seed(0)
np.random.rand(3, 3)

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276]])

In [4]:
np.random.seed(42)

In [5]:
np.random.rand(3, 3)

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501]])

In [11]:
mat1 = np.random.rand(3, 3)
mat2 = np.random.rand(3, 3)
print(mat1)
print(f"\n")
print(mat2)

[[0.35675333 0.28093451 0.54269608]
 [0.14092422 0.80219698 0.07455064]
 [0.98688694 0.77224477 0.19871568]]


[[0.00552212 0.81546143 0.70685734]
 [0.72900717 0.77127035 0.07404465]
 [0.35846573 0.11586906 0.86310343]]


## Array operations

In [12]:
# multiplies vector by vector
np.dot(mat1, mat2)

array([[0.40131125, 0.57047672, 0.74137826],
       [0.6123094 , 0.74226713, 0.22335664],
       [0.63965444, 1.42340272, 0.92628106]])

In [13]:
# multiplies element by element
np.multiply(mat1, mat2)

array([[0.00197003, 0.22909126, 0.38360871],
       [0.10273477, 0.61871074, 0.00552008],
       [0.35376514, 0.08947928, 0.17151219]])

In [14]:
# sums the line
sum1 = np.sum(mat1, axis=0)
print(sum1)
# sums the column 
sum2 = np.sum(mat1, axis=1)
print(sum2)

[1.48456449 1.85537626 0.81596241]
[1.18038392 1.01767185 1.95784739]
